image: ubuntu/lts
packages:
  - nodejs
  - postgresql
  - curl
  - git-core
  - zlib1g-dev
  - build-essential
  - libssl-dev
  - libreadline-dev
  - libyaml-dev
  - libsqlite3-dev
  - sqlite3
  - libxml2-dev
  - libxslt1-dev
  - libcurl4-openssl-dev
  - software-properties-common
  - libffi-dev
  - libpq-dev
  - yarn
sources:
  - https://git.sr.ht/~voloyev/cafefilo_v3
tasks:
  - setup: |
      cd
      gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
      curl -sSL https://get.rvm.io | bash
      cd cafefilo_v3
      source ~/.rvm/scripts/rvm
      rvm install $(cat .ruby-version)
      sudo -u postgres psql -c "create role test with  createdb login password 'secret';"
      sudo -u postgres psql -c "alter user test with superuser;"
  - build: |
      cd cafefilo_v3
      source ~/.rvm/scripts/rvm
      rvm use $(cat .ruby-version)
      export RAILS_ENV='test'
      export CAFEPHILO_V3_DATABASE_TEST_USER=test
      export CAFEPHILO_V3_DATABASE_TEST_NAME=test_db
      export CAFEPHILO_V3_DATABASE_TEST_PASSWORD=secret
      gem install bundler:1.17.3 --user-install
      export PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"
      bundle install --no-system
      rake db:create
      rake db:migrate
  - test: |
      cd cafefilo_v3
      source ~/.rvm/scripts/rvm
      rvm use $(cat .ruby-version)
      export CAFEPHILO_V3_DATABASE_TEST_USER=test
      export CAFEPHILO_V3_DATABASE_TEST_NAME=test_db
      export CAFEPHILO_V3_DATABASE_TEST_PASSWORD=secret
      RAILS_ENV='test' bundle exec rspec spec
