image: ubuntu/latest
packages:
  - nodejs
  - ruby
  - postgresql
sources:
  - https://git.sr.ht/~voloyev/cafefilo_v3
tasks:
  - setup: |
      sudo -u postgres createuser -d -l -r -w test
      export DATABASE_TEST_NAME='test_db'
      export DATABASE_TEST_USER='test'
      gem install bundler
      bundle install
      rake db:create
      rake db:migrate
  - test: |
      RAILS_ENV='test' bundle exec rspec spec
