version: '3'
services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/cafephilo_app
    ports:
      - "3000:3000"
    depends_on:
      - db
