default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  username: <%= ENV.fetch('DATABASE_USER') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
  database: <%= ENV.fetch('DATABASE_NAME') %>


test:
  <<: *default
  username: <%= ENV.fetch('DATABASE_TEST_USER') %>
  password: <%= ENV.fetch('DATABASE_TEST_PASSWORD') %>
  database: <%= ENV.fetch('DATABASE_TEST_NAME') %>


production:
  <<: *default
  database: cafephilo_v3_production
  username: cafephilo_v3
  password: <%= ENV['CAFEPHILO_V3_DATABASE_PASSWORD'] %>
