default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("CAFEPHILO_V3_DATABASE_HOST", 'localhost') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

staging:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('CAFEPHILO_V3_DATABASE_STAGING_HOST', nil) %>
  username: <%= ENV.fetch('CAFEPHILO_V3_DATABASE_STAGING_USER', nil) %>
  password: <%= ENV.fetch('CAFEPHILO_V3_DATABASE_STAGING_PASSWORD', nil) %>
  database: <%= ENV.fetch('CAFEPHILO_V3_DATABASE_STAGING_NAME', nil) %>

development:
  <<: *default
  username: <%= ENV.fetch('CAFEPHILO_V3_DATABASE_USER', nil) %>
  password: <%= ENV.fetch('CAFEPHILO_V3_DATABASE_PASSWORD', nil) %>
  database: <%= ENV.fetch('CAFEPHILO_V3_DATABASE_NAME', nil) %>

test:
  <<: *default
  username: <%= ENV.fetch('CAFEPHILO_V3_DATABASE_TEST_USER', nil) %>
  password: <%= ENV.fetch('CAFEPHILO_V3_DATABASE_TEST_PASSWORD', nil) %>
  database: <%= ENV.fetch('CAFEPHILO_V3_DATABASE_TEST_NAME', nil) %>

production:
  <<: *default
  database: <%= ENV['CAFEPHILO_V3_DATABASE_PRODUCTION_NAME'] %>
  username: <%= ENV['CAFEPHILO_V3_DATABASE_PRODUCTION_USER'] %>
  password: <%= ENV['CAFEPHILO_V3_DATABASE_PRODUCTION_PASSWORD'] %>
