default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

staging:
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('CAFEPHILO_V3_DATABASE_STAGING_USER', nil) %>
  password: <%= ENV.fetch('CAFEPHILO_V3_DATABASE_STAGING_PASSWORD', nil) %>
  database: <%= ENV.fetch('CAFEPHILO_V3_DATABASE_STAGING_NAME', nil) %>

development:
  <<: *default
  username: <%= ENV.fetch('CAFEPHILO_V3_DATABASE_USER', nil) %>
  password: <%= ENV.fetch('CAFEPHILO_V3_DATABASE_PASSWORD', nil) %>
  database: <%= ENV.fetch('CAFEPHILO_V3_DATABASE_NAME', nil) %>

test:
  <<: *default
  username: <%= ENV.fetch('CAFEPHILO_V3_DATABASE_TEST_USER', nil) %>
  password: <%= ENV.fetch('CAFEPHILO_V3_DATABASE_TEST_PASSWORD', nil) %>
  database: <%= ENV.fetch('CAFEPHILO_V3_DATABASE_TEST_NAME', nil) %>



production:
  <<: *default
  database: cafephilo_v3_production
  username: cafephilo_v3
  password: <%= ENV['CAFEPHILO_V3_DATABASE_PASSWORD'] %>
