# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Rails

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: rails_github_actions
          POSTGRES_DB: rails_github_actions_test
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      # if you need redis
      redis:
         image: redis
         ports:
          - 6379:6379
         options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: setup cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.17.0
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -yqq install libpq-dev build-essential libcurl4-openssl-dev
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          yarn install
      - name: Run Linter
        run: |
          bundle exec rubocop app lib spec
      - name: Setup test database
        env:
          RAILS_ENV: test
          CAFEPHILO_V3_DATABASE_TEST_NAME: rails_github_actions_test
          CAFEPHILO_V3_DATABASE_TEST_USER: rails_github_actions
          CAFEPHILO_V3_DATABASE_TEST_PASSWORD: postgres
        run: |
          bundle exec rake db:create db:migrate
      - name: Run tests
        env:
          CAFEPHILO_V3_DATABASE_TEST_NAME: rails_github_actions_test
          CAFEPHILO_V3_DATABASE_TEST_USER: rails_github_actions
          CAFEPHILO_V3_DATABASE_TEST_PASSWORD: postgres
          PGPORT: ${{ job.services.postgres.ports[5432] }}
          RAILS_ENV: test
        run: |
          bundle exec rspec
